# Generated by Django 4.2.4 on 2023-08-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static/twitter/default.png', upload_to='media/twitter/'),
        ),
    ]
