# Generated by Django 4.2.4 on 2023-08-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
