# Generated by Django 4.2.4 on 2023-08-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_comment_comments_commentundercomment_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.user2')),
            ],
        ),
    ]
