# Generated by Django 4.2.4 on 2023-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(related_name='post_like', to='twitter.user2'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
