# Generated by Django 4.2.3 on 2023-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_rename_comments_post_commentscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user2',
            name='following',
            field=models.ManyToManyField(related_name='follow_account', to='twitter.follow'),
        ),
    ]
