# Generated by Django 4.2.3 on 2023-08-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_follow_user2_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowObj',
        ),
    ]
