# Generated by Django 4.2.4 on 2023-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_rename_follow_followobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likedBy',
            field=models.ManyToManyField(related_name='comment_like', to='twitter.user2'),
        ),
        migrations.AddField(
            model_name='commentundercomment',
            name='likedBy',
            field=models.ManyToManyField(related_name='commentplus_like', to='twitter.user2'),
        ),
    ]
