# Generated by Django 4.2.4 on 2023-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_user2_followers_user2_followingnum_user2_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_post', to='twitter.post'),
        ),
    ]
