# Generated by Django 4.2.4 on 2023-08-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0016_user2_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user2',
            name='ownlists',
            field=models.ManyToManyField(related_name='own_list', to='twitter.postlist'),
        ),
        migrations.AddField(
            model_name='user2',
            name='savedlists',
            field=models.ManyToManyField(related_name='saved_list', to='twitter.postlist'),
        ),
    ]
