# Generated by Django 4.2.4 on 2023-08-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0017_postlist_user2_ownlists_user2_savedlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='name',
            field=models.CharField(default='List', max_length=200),
        ),
        migrations.AddField(
            model_name='postlist',
            name='numPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postlist',
            name='posts',
            field=models.ManyToManyField(related_name='listed_post', to='twitter.post'),
        ),
        migrations.AddField(
            model_name='postlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.user2'),
        ),
    ]
