# Generated by Django 4.2.3 on 2023-08-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0021_notification_user2_notificationlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
