# Generated by Django 4.2.3 on 2023-09-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0022_notification_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first', to='twitter.user2')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second', to='twitter.user2')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.messageboard')),
            ],
        ),
    ]
