# Generated by Django 4.2.3 on 2023-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0025_alter_messageboard_last_messaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='last_messaged',
            field=models.DateTimeField(verbose_name='last message'),
        ),
    ]
